---
image: gitlab-registry.cern.ch/linuxsupport/cc7-base
stages:
  - build
  - test
  - build_rpm
  - koji_scratch
  - koji
  - deploy_qa
  - deploy_prod


before_script:
  - yum -y install golang git
  - export GOPATH=/go
  - go get github.com/tools/godep
  - pwd
  - ls -al 
  - mkdir -p /go/src/github.com/cernops/
  - ln -s  /builds/lb-experts/golbd /go/src/github.com/cernops/golbd
  - cd /go/src/github.com/cernops/golbd
  - export SPEC=$(ls *spec)
  - export PKG=$(rpm -q --specfile $SPEC --queryformat "%{name}-%{version}\n" | head -n 1)
  - export PKG_REL=$(rpm -q --specfile $SPEC --queryformat "%{name}-%{version}-%{release}\n" | head -n 1)
  - echo $LBBUILD_PASSWORD | kinit lbbuild@CERN.CH
  - klist
  - printf "[koji]\nserver = http://koji.cern.ch/kojihub\nweburl = http://koji.cern.ch/koji\ntopurl = http://koji.cern.ch/kojifiles\ncert    = /not/existing/file" > .koji

build-my-project:
  stage: build
  script:
    - /go/bin/godep restore
    - /go/bin/godep go build

test-my-project:
  stage: test
  script:
    - /go/bin/godep restore
    - /go/bin/godep go test -v -cover ./...

build_rpm:
  stage: build_rpm
  script:
    - mkdir SOURCES
    - tar zcvf SOURCES/$PKG.tgz  --exclude SOURCES --exclude .git --exclude .koji --exclude .gitlab-ci.yml --transform "s||$PKG/|" .
    - rpmbuild -bs --define "_topdir $(pwd)" -D "dist ${DIST:-.ai7}" $SPEC
  artifacts:
    paths:
      - SRPMS/
    expire_in: 1 week


kojicheck:
  stage: koji_scratch
  script:
    - echo "Checking if $PKG_REL exists"
    - if koji search -r build $PKG | grep $PKG_REL; then exit 1; fi
kojiscratch:
  stage: koji_scratch
  script:
    - export SRPM="SRPMS/${PKG_REL}.src.rpm"
    - echo "koji build --wait --scratch $KOJI_TARGET $SRPM"
    - koji build --wait --scratch $KOJI_TARGET $SRPM

koji:
  stage: koji
  script:
    - export SRPM="SRPMS/${PKG_REL}.src.rpm"
    - echo "koji build --wait $KOJI_TARGET $SRPM"
    - koji build --wait $KOJI_TARGET $SRPM
  only:
    - tags

tag_qa:
  stage: deploy_qa
  when: manual
  only:
    - tags
  script:
    - koji --config=.koji tag-pkg ${KOJI_TARGET}-qa ${PKG_REL}
  allow_failure: false

tag_prod:
  stage: deploy_prod
  when: manual
  only:
    - tags
  script:
    - koji --config=.koji tag-pkg ${KOJI_TARGET}-stable ${PKG_REL}

