---
include:
  - 'https://gitlab.cern.ch/linuxsupport/rpmci/raw/master/rpm-ci.yml'

variables:
  KOJI_TAG: 'lb'
  KOJI_TAG_7: 'ai7'

  BUILD_7: 'True'
  BUILD_8: 'True'

  DIST_8: .el8
  DIST_7: .ai7


.install_go: &install_go |
    mkdir -p /go13
    yum -y install git gcc
    curl https://dl.google.com/go/go1.13.14.linux-amd64.tar.gz  | tar -zxC /go13
    rm -f /usr/bin/go
    ln -s /go13/go/bin/go /usr/bin/go
    export GOPATH=/go13

build-my-project:
  stage: prebuild
  script:
    - *install_go
    - go build
    - go build -race

fmt-my-project:
  stage: prebuild
  script:
    - *install_go
    - MOD_FILES=$(find . -name "*.go"  -exec /usr/bin/go fmt {} \;)
    - echo "FILES MODIFIED $MOD_FILES"
    - if [ "$MOD_FILES" != "" ]; then false; fi

test-my-project:
  stage: prebuild
  script:
    - *install_go
    - go test -v -cover ./...
    - go test -race
