---
image: gitlab-registry.cern.ch/linuxsupport/cc7-base

include: 
  - project: lb-experts/golbclient
    ref: psaiz_devel
    file: .gitlab-ci_koji.yml

before_script:
  - yum -y install --exclude python2-libcomps  krb5-workstation koji rpm-build rpmdevtools
  - mkdir -p /go/src/github.com/cernops/
  - ln -s  /builds/lb-experts/golbd /go/src/github.com/cernops/golbd
  - cd /go/src/github.com/cernops/golbd
  - export SPEC=$(ls *spec)
  - export PKG=$(rpm -q --specfile $SPEC --queryformat "%{name}-%{version}\n" | head -n 1)
  - export PKG_REL7=$(rpm -q --specfile $SPEC --queryformat "%{name}-%{version}-%{release}\n" | head -n 1)
  - export PKG_REL8=$(rpm -q --define "dist .lb8" --specfile $SPEC --queryformat "%{name}-%{version}-%{release}\n" | head -n 1)

