---
image: gitlab-registry.cern.ch/linuxsupport/cc7-base

include: 
  - project: lb-experts/golbclient
    ref: master
    file: .gitlab-ci.yml

before_script:
  - echo "FROM THE GOLBD"
  - ln -s  /builds/lb-experts/golbd /go/src/github.com/cernops/golbd
  - cd /go/src/github.com/cernops/golbd
  - export SPEC=$(ls *spec)
  - export PKG=$(rpm -q --specfile $SPEC --queryformat "%{name}-%{version}\n" | head -n 1)
  - export PKG_REL=$(rpm -q --specfile $SPEC --queryformat "%{name}-%{version}-%{release}\n" | head -n 1)
