---
include:
  - 'https://gitlab.cern.ch/linuxsupport/rpmci/raw/master/rpm-ci.yml'

variables:
  KOJI_TAG: 'lb'
  KOJI_TAG_7: 'ai7'

  BUILD_7: 'True'
  BUILD_8: 'True'

  DIST_8: .el8
  DIST_7: .ai7


.install_godep: &install_godep |
  yum -y install golang git gcc
  export GOPATH=/go
  go get github.com/tools/godep
  /go/bin/godep restore

build-my-project:
  stage: prebuild
  script:
    - *install_godep
    - /go/bin/godep go build
    - /go/bin/godep go build -race

fmt-my-project:
  stage: prebuild
  script:
    - yum -y install golang git gcc
    - export GOPATH=/go
    - mkdir /go11
    - curl https://dl.google.com/go/go1.11.2.linux-amd64.tar.gz | tar -zxC /go11
    - MOD_FILES=$(find . -name "*.go"  -exec /go11/go/bin/go fmt {} \;)
    - echo "FILES MODIFIED $MOD_FILES"
    - if [ "$MOD_FILES" != "" ]; then false; fi

test-my-project:
  stage: prebuild
  script:
    - *install_godep
    - /go/bin/godep go test -v -cover ./...
    - /go/bin/godep go test -race
