---
#image: golang:1.7-alpine
image: gitlab-registry.cern.ch/cloud/ciadm
stages:
  - build
  - test
  - deploy

before_script:
  - yum -y install golang git
  - export GOPATH=/go
  - go get github.com/tools/godep
  - pwd
  - ls -al 
  - mkdir -p /go/src/github.com/cernops/
  - ln -s  /builds/lb-experts/golbd /go/src/github.com/cernops/golbd
  - cd /go/src/github.com/cernops/golbd

build-my-project:
  stage: build
  script:
    - pwd
    - ls -al 
    - cd /go/src/github.com/cernops/golbd
    - /go/bin/godep restore
    - /go/bin/godep go build

test-my-project:
  stage: test
  script:
    - /go/bin/godep restore
    - /go/bin/godep go test -v -cover ./...

kojicheck:
  stage: deploy
  script:
#    - curl https://gitlab.cern.ch/cloud-infrastructure/cloud-dev/raw/master/gitlab/kojicheck.sh | bash
    - cd $CI_PROJECT_DIR
    - export SPEC=$(ls *spec)
    - echo SPEC=$SPEC
    - export PKG=$(rpm -q --specfile $SPEC --queryformat "%{name}-%{version}-%{release}")
    - echo $SVCBUILD_PASSWORD | kinit svcbuild@CERN.CH
    - if koji search -r build $PKG | grep $PKG; then exit 1; fi
#kojiscratch:
#  stage: deploy
##  image: gitlab-registry.cern.ch/cloud/ciadm
#  script:
#    - export SCRATCH=1
#    - curl https://gitlab.cern.ch/cloud-infrastructure/cloud-dev/raw/master/gitlab/kojibuild.sh | bash

